### ISSUE TITLE
StaticFiles get clobbered

### ISSUE THREAD

**Issue by brendanmig** [pixijs/pixi-jsdoc-template#15]
When specifying staticFiles on an operating system whose directory separator doesn't match the directory separator used in the config file, EG:

`"path": [ "./static/docs" ]`

when running on an OS whose directory separator is `\` the template attempts to copy the files in the path over themselves resulting in 0 byte files.

additionally, the jsdoc documented 'include' path doesn't work, it has to be 'path' as above.

**Comment by bigtimebuddy** [comment]
Fixed in latest release v2.5.1
