### ISSUE TITLE
Inject custom CSS

### ISSUE THREAD

**Issue by sanbornhilland** [pixijs/pixi-jsdoc-template#25]
It would be useful to be able to inject custom CSS to make small overrides without having to fork the project. Something like the [docdash](https://github.com/clenemt/docdash) `scripts` config would be enough. 

Are you open to a PR for this?

**Comment by bigtimebuddy** [comment]
Definitely. Good idea!

**Comment by sanbornhilland** [comment]
@bigtimebuddy Okay I'm going to essentially take the same approach as they did in `docdash`. My one question is where config values should go. On that project they've added a `docdash` key that contains all the specific configuration for that project. I'm generally familiar with `jsdoc` but it's a little unclear to me what config is default and what is additional to each custom template. 

Does it make sense to have `templates.scripts` or `templates.pixi.scripts`?

**Comment by bigtimebuddy** [comment]
I’m not sure either. We aren’t JSDoc experts over here, so I’d take the lead on how other packages like docdash do it.
