### ISSUE TITLE
Member name readability

### ISSUE THREAD

**Issue by digibo** [pixijs/pixi-jsdoc-template#3]
First, thanks to everyone involved in the latest update! Docs are important and besides some things mentioned here, I love the facelift.

In my use case of the documentation, which is quickly scrolling through a class' member list to find a specific description/signature, I find the new docs slightly harder to work with. Member/method names aren't as distinct as before (used to be bold) and tags (inherited, static, etc.) steal the spotlight most of the time. The member type listed after the name uses a smaller font, but it usually starts with the uppercase PIXI, so it also overshadows the member/method name.

Inherited _method_ names being colored gray adds to the issue (bold and darker gray remedied this before) and there is also a discrepancy with inherited _members'_ names not being grayed in the main area while being darker in the navigation on the left (a very minor issue IMO).

Overall, I feel member names are getting lost amidst the rest of the text. Maybe it's just me not using the navigation on the left (which is 1000% more awesome now), but I'm used to scrolling through the main centered(:+1:) blob of text.

**Comment by bigtimebuddy** [comment]
Good comment. @digibo would love your feedback on #4
